<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="54" started-at="2015-03-13T07:51:31Z" finished-at="2015-03-13T07:51:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="54" started-at="2015-03-13T07:51:31Z" finished-at="2015-03-13T07:51:31Z">
      <class name="TestXML.SampleTest">
        <test-method status="FAIL" signature="testMethodTwo()[pri:0, instance:TestXML.SampleTest@18e8568]" name="testMethodTwo" duration-ms="20" started-at="2015-03-13T03:51:31Z" finished-at="2015-03-13T03:51:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at TestXML.SampleTest.testMethodTwo(SampleTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethodTwo -->
        <test-method status="PASS" signature="testMethodOne()[pri:0, instance:TestXML.SampleTest@18e8568]" name="testMethodOne" duration-ms="1" started-at="2015-03-13T03:51:31Z" finished-at="2015-03-13T03:51:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethodOne -->
        <test-method status="SKIP" signature="testMethodThree()[pri:0, instance:TestXML.SampleTest@18e8568]" name="testMethodThree" duration-ms="2" started-at="2015-03-13T03:51:31Z" depends-on-methods="TestXML.SampleTest.testMethodTwo" finished-at="2015-03-13T03:51:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethodThree -->
      </class> <!-- TestXML.SampleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
